# Generated by Django 4.0.1 on 2022-01-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_picture_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='ano_de_criacao',
        ),
        migrations.AddField(
            model_name='picture',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='Ano de criação'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pais',
            field=models.CharField(default='', max_length=50, verbose_name='País'),
        ),
    ]
