# Generated by Django 4.0.1 on 2022-01-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_picture_ano_de_criacao_picture_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='imagem',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
